### ISSUE TITLE
Kotlin 1.4.0 compatibility

### ISSUE THREAD

**Issue by kihaki** [natario1/Egloo#26]
Hey, it seems that egloo has a compatibility issue with kotlin 1.4

```
java.lang.NoSuchMethodError: No static method get-impl([II)I in class Lkotlin/UIntArray; or its super classes (declaration of 'kotlin.UIntArray' appears in [...]
        at com.otaliastudios.opengl.texture.GlTexture.<init>(GlTexture.kt:90)
        at com.otaliastudios.opengl.texture.GlTexture.<init>(GlTexture.kt:30)
        at com.otaliastudios.opengl.texture.GlTexture.<init>(GlTexture.kt:29)
...
```

**Comment by kihaki** [comment]
Thank you for the fix, appreciate the good work! :)

**Comment by natario1** [comment]
Not sure it's fixed, but I hope so! Thanks :-)

**Comment by kihaki** [comment]
It did fix the issue for me at least :)
